/**
 * Document export utilities for generating DOC and PDF files with formatting
 */

import { Document, Paragraph, TextRun, HeadingLevel, Packer, AlignmentType } from 'docx'
import { jsPDF } from 'jspdf'
import { parseTextFormatting, FormattedText } from './text-formatter'

export interface ExportOptions {
  filename: string
  title?: string
  author?: string
  includeMetadata?: boolean
}

/**
 * Generate a DOCX document from formatted text
 */
export async function generateDOCX(
  text: string,
  options: ExportOptions
): Promise<Blob> {
  const formatted = parseTextFormatting(text)
  const children: Paragraph[] = []

  // Add title if provided
  if (options.title) {
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: options.title,
            bold: true,
            size: 32
          })
        ],
        alignment: AlignmentType.CENTER,
        spacing: { after: 400 }
      })
    )
  }

  // Convert formatted blocks to DOCX paragraphs
  for (const block of formatted.blocks) {
    switch (block.type) {
      case 'header':
        const headingLevel = Math.min(block.level || 1, 6) as 1 | 2 | 3 | 4 | 5 | 6
        const headingLevelMap: Record<number, HeadingLevel> = {
          1: HeadingLevel.HEADING_1,
          2: HeadingLevel.HEADING_2,
          3: HeadingLevel.HEADING_3,
          4: HeadingLevel.HEADING_4,
          5: HeadingLevel.HEADING_5,
          6: HeadingLevel.HEADING_6
        }
        
        children.push(
          new Paragraph({
            children: [new TextRun(block.content)],
            heading: headingLevelMap[headingLevel],
            spacing: { before: 240, after: 120 }
          })
        )
        break

      case 'bold':
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: block.content,
                bold: true
              })
            ],
            spacing: { after: 120 }
          })
        )
        break

      case 'italic':
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: block.content,
                italics: true
              })
            ],
            spacing: { after: 120 }
          })
        )
        break

      case 'list':
        children.push(
          new Paragraph({
            children: [
              new TextRun('• '),
              new TextRun(block.content)
            ],
            spacing: { after: 120 }
          })
        )
        break

      case 'blank_line':
        children.push(
          new Paragraph({
            children: [new TextRun('')],
            spacing: { after: 120 }
          })
        )
        break

      case 'paragraph':
      default:
        if (block.content.trim()) {
          children.push(
            new Paragraph({
              children: [new TextRun(block.content)],
              spacing: { after: 120 }
            })
          )
        }
        break
    }
  }

  const doc = new Document({
    sections: [
      {
        properties: {},
        children
      }
    ],
    creator: options.author || 'LoreTrans',
    title: options.title || options.filename,
    description: 'Generated by LoreTrans Translation Service'
  })

  const buffer = await Packer.toBuffer(doc)
  return new Blob([buffer], {
    type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  })
}

/**
 * Generate a PDF document from formatted text
 */
export function generatePDF(
  text: string,
  options: ExportOptions
): Blob {
  const formatted = parseTextFormatting(text)
  const pdf = new jsPDF()
  
  let yPosition = 20
  const pageHeight = pdf.internal.pageSize.height
  const margin = 20
  const lineHeight = 7
  const maxWidth = pdf.internal.pageSize.width - 2 * margin

  // Add title if provided
  if (options.title) {
    pdf.setFontSize(18)
    pdf.setFont('helvetica', 'bold')
    pdf.text(options.title, pdf.internal.pageSize.width / 2, yPosition, { align: 'center' })
    yPosition += 20
  }

  // Process formatted blocks
  for (const block of formatted.blocks) {
    // Check if we need a new page
    if (yPosition > pageHeight - 30) {
      pdf.addPage()
      yPosition = 20
    }

    switch (block.type) {
      case 'header':
        const headerSize = Math.max(16 - (block.level || 1) * 2, 12)
        pdf.setFontSize(headerSize)
        pdf.setFont('helvetica', 'bold')
        
        const headerLines = pdf.splitTextToSize(block.content, maxWidth)
        pdf.text(headerLines, margin, yPosition)
        yPosition += headerLines.length * lineHeight + 5
        break

      case 'bold':
        pdf.setFontSize(12)
        pdf.setFont('helvetica', 'bold')
        
        const boldLines = pdf.splitTextToSize(block.content, maxWidth)
        pdf.text(boldLines, margin, yPosition)
        yPosition += boldLines.length * lineHeight + 3
        break

      case 'italic':
        pdf.setFontSize(12)
        pdf.setFont('helvetica', 'italic')
        
        const italicLines = pdf.splitTextToSize(block.content, maxWidth)
        pdf.text(italicLines, margin, yPosition)
        yPosition += italicLines.length * lineHeight + 3
        break

      case 'list':
        pdf.setFontSize(12)
        pdf.setFont('helvetica', 'normal')
        
        const listContent = '• ' + block.content
        const listLines = pdf.splitTextToSize(listContent, maxWidth)
        pdf.text(listLines, margin, yPosition)
        yPosition += listLines.length * lineHeight + 2
        break

      case 'blank_line':
        yPosition += lineHeight
        break

      case 'paragraph':
      default:
        if (block.content.trim()) {
          pdf.setFontSize(12)
          pdf.setFont('helvetica', 'normal')
          
          const paragraphLines = pdf.splitTextToSize(block.content, maxWidth)
          pdf.text(paragraphLines, margin, yPosition)
          yPosition += paragraphLines.length * lineHeight + 3
        }
        break
    }
  }

  // Add metadata
  if (options.includeMetadata !== false) {
    pdf.setProperties({
      title: options.title || options.filename,
      creator: options.author || 'LoreTrans',
      producer: 'LoreTrans Translation Service'
    })
  }

  return new Blob([pdf.output('arraybuffer')], { type: 'application/pdf' })
}

/**
 * Download a blob as a file
 */
export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Generate and download DOCX file
 */
export async function downloadDOCX(
  text: string,
  options: ExportOptions
): Promise<void> {
  const blob = await generateDOCX(text, options)
  const filename = options.filename.endsWith('.docx') 
    ? options.filename 
    : `${options.filename}.docx`
  downloadBlob(blob, filename)
}

/**
 * Generate and download PDF file
 */
export function downloadPDF(
  text: string,
  options: ExportOptions
): void {
  const blob = generatePDF(text, options)
  const filename = options.filename.endsWith('.pdf') 
    ? options.filename 
    : `${options.filename}.pdf`
  downloadBlob(blob, filename)
}

/**
 * Get file size in human readable format
 */
export function getFileSizeString(bytes: number): string {
  if (bytes === 0) return '0 Bytes'
  
  const k = 1024
  const sizes = ['Bytes', 'KB', 'MB', 'GB']
  const i = Math.floor(Math.log(bytes) / Math.log(k))
  
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i]
}

/**
 * Validate text content for export
 */
export function validateExportContent(text: string): {
  isValid: boolean
  error?: string
  warnings?: string[]
} {
  const warnings: string[] = []
  
  if (!text || text.trim().length === 0) {
    return {
      isValid: false,
      error: 'No content to export'
    }
  }
  
  if (text.length > 50000) {
    warnings.push('Large content may affect export performance')
  }
  
  const formatted = parseTextFormatting(text)
  if (!formatted.hasFormatting) {
    warnings.push('No formatting detected - exporting as plain text')
  }
  
  return {
    isValid: true,
    warnings: warnings.length > 0 ? warnings : undefined
  }
}